# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
# kubectl create secret docker-registry docker-pull-credentials --docker-server=hub.itgo-devops.org:18443 --docker-username=itgo-hit-imaki --docker-password=;aA9g6U[}uze-BN4Lw"b --docker-email=noreply@itgo-devops.org
# kubectl get secret docker-pull-credentials --output=yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-pull-credentials
  namespace: sample-rest-ws
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJodWIuaXRnby1kZXZvcHMub3JnOjE4NDQzIjp7InVzZXJuYW1lIjoiaXRnby1oaXQtaW1ha2kiLCJwYXNzd29yZCI6IjthQTlnNlVbfXV6ZS1CTjRMd1wiYiIsImVtYWlsIjoibm9yZXBseUBpdGdvLWRldm9wcy5vcmciLCJhdXRoIjoiYVhSbmJ5MW9hWFF0YVcxaGEyazZPMkZCT1djMlZWdDlkWHBsTFVKT05FeDNJbUk9In19
---