apiVersion: v1
kind: Service
metadata:
  name: sample-rest-ws-external
  namespace: sample-rest-ws
  labels:
    app: sample-rest-ws-external
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: sample-rest-ws-ds
